{
 "title": "Stocks",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Major Stocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SE Major 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('GICRE','NIACL','JUSTDIAL','CUMMINSIND','MANKIND','LICI','MOTILALOFS','BDL','TRENT','TTML','HAL','POWERGRID','ELGIEQUIP','JINDALSAW','INDIANB','STARCEMENT','FSL','NLCINDIA','SBIN','VMART','POLYMED','RENUKA','GLAND','PEL','ZFCVINDIA','CRAFTSMAN','GODREJPROP') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "SE Major 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ZEEL','MIDHANI','METROBRAND','OIL','TATACOMM','CANBK','LUXIND','CRISIL','360ONE','COCHINSHIP','HFCL','BANKBARODA','PIIND','NETWORK18','PCBL','BPCL','JSWENERGY','KALYANKJIL','ALKEM','TORNTPOWER') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "SE Major 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('CDSL','COALINDIA','BIRLACORPN','INTELLECT','BANKINDIA','ERIS','CONCOR','GUJALKALI','MFSL','CAMS','KPITTECH','LEMONTREE','MAXHEALTH','BEL','SAFARI','SWSOLAR','VOLTAS','USHAMART','AUROPHARMA','OFSS') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "SE Major 4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('OBEROIRLTY','PNCINFRA','EPL','KEC','PGHL','ZOMATO','INFIBEAM','VTL','TATAPOWER','MAZDOCK','CSBBANK','AEGISCHEM','FINEORG','UNIONBANK','ANGELONE','SJVN','MSUMI','CAPLIPOINT','PAYTM','BORORENEW','IOB','BALRAMCHIN','DALBHARAT','KIOCL','SYNGENE','FLUOROCHEM') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "SE Major 5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('UCOBANK','VARROC','PSB','AIAENG','JKPAPER','METROPOLIS','CENTRALBK','MUTHOOTFIN','JYOTHYLAB','MAHABANK','BRIGADE','MMTC','CHAMBLFERT','DELTACORP','MANAPPURAM','ITC','BRITANNIA','CANFINHOME','NYKAA','ABB','AMBER','FINCABLES','GLENMARK','MEDPLUS') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "SE Major 6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('CREDITACC','CHOLAFIN','ECLERX','SOBHA','AUBANK','TATACONSUM','NESTLEIND','GRINDWELL','AARTIIND','JWL','LATENTVIEW','FDC','BEML','EICHERMOT','TIMKEN','LALPATHLAB','FORTIS','PIDILITIND','JAMNAAUTO','AXISBANK','STLTECH') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
    }
   ]
  },
  {
   "title": "Sector Indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nifty IT",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('COFORGE','HCLTECH','INFY','LTTS','LTIM','MPHASIS','PERSISTENT','TCS','TECHM','WIPRO') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty FINANCE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('AAVAS','ABCAPITAL','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','CHOLAFIN','DHANI','GICRE','HDFCAMC','HDFCLIFE','HDFC','ICICIGI','ICICIPRULI','IDFC','IBULHSGFIN','IEX','L&TFH','LICHSGFIN','M&MFIN','MANAPPURAM','MFSL','MCX','MUTHOOTFIN','PEL','PFC','RECLTD','SBICARD','SBILIFE','SRTRANSFIN','SUNDARMFIN') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty MSCAP IT TELCO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('BSOFT','COFORGE','CYIENT','FSL','HFCL','HAPPSTMNDS','INTELLECT','KPITTECH','LTTS','MASTEK','MPHASIS','OFSS','PERSISTENT','ROUTE','SONATSOFTW','STLTECH','TATACOMM','TATAELXSI','IDEA','ZENSARTECH') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty Bank",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('AUBANK','AXISBANK','BANDHANBNK','BANKBARODA','FEDERALBNK','HDFCBANK','ICICIBANK','IDFCFIRSTB','INDUSINDBK','KOTAKBANK','PNB','SBIN') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty HEALTHCARE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('GLAND','GLAXO','NATCOPHARM','PFIZER','SANOFI','ABBOTINDIA','ALKEM','APOLLOHOSP','AUROPHARMA','BIOCON','CIPLA','DIVISLAB','LALPATHLAB','DRREDDY','GLENMARK','GRANULES','IPCALAB','LAURUSLABS','LUPIN','MAXHEALTH','METROPOLIS','SUNPHARMA','SYNGENE','TORNTPHARM','ZYDUSLIFE') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty OIL & GAS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ATGL','AEGISCHEM','BPCL','CASTROLIND','GAIL','GUJGASLTD','GSPL','HINDPETRO','IOC','IGL','MGL','ONGC','OIL','PETRONET','RELIANCE') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty REALTY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('BRIGADE','DLF','GODREJPROP','LODHA','MAHLIFE','OBEROIRLTY','PHOENIXLTD','PRESTIGE','SOBHA','SWANENERGY') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty METAL",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 23 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('APLAPOLLO','ADANIENT','HINDALCO','HINDCOPPER','HINDZINC','JSWSTEEL','JSL','JINDALSTEL','NMDC','NATIONALUM','RATNAMANI','SAIL','TATASTEEL','VEDL','WELCORP') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty CONSUMER DURABLES",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 23 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('AMBER','BATAINDIA','BLUESTARCO','CROMPTON','DIXON','HAVELLS','KAJARIACER','ORIENTELEC','RAJESHEXPO','RELAXO','TTKPRESTIG','TITAN','VGUARD','VOLTAS','WHIRLPOOL') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty Auto",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 30 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ASHOKLEY','BAJAJ-AUTO','BALKRISIND','BHARATFORG','BOSCHLTD','EICHERMOT','HEROMOTOCO','MRF','M&M','MARUTI','MOTHERSON','SONACOMS','TVSMOTOR','TATAMOTORS','TIINDIA') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty MEDIA",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 30 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('DBCORP','DISHTV','HATHWAY','NAZARA','NETWORK18','PVRINOX','SAREGAMA','SUNTV','TV18BRDCST','ZEEL') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty FMCG",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 30 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('BRITANNIA','COLPAL','DABUR','EMAMILTD','GODREJCP','HINDUNILVR','ITC','MARICO','NESTLEIND','PGHH','RADICO','TATACONSUM','UBL','MCDOWELL-N','VBL') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty MSCAP FINTECH",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 37 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('AUBANK','AAVAS','ABCAPITAL','BANDHANBNK','CRISIL','CDSL','CHOLAHLDNG','CUB','CAMS','FEDERALBNK','HDFCAMC','IDFCFIRSTB','IDFC','IIFL','IEX','L&TFH','LICHSGFIN','M&MFIN','MANAPPURAM','MFSL','MCX','PAYTM','POLICYBZR','PEL','POONAWALLA','PFC','RBLBANK','RECLTD','SUNDARMFIN','YESBANK') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "Broad Indices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nifty 50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ADANIENT','ADANIPORTS','APOLLOHOSP','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BPCL','BHARTIARTL','BRITANNIA','CIPLA','COALINDIA','DIVISLAB','DRREDDY','EICHERMOT','GRASIM','HCLTECH','HDFCBANK','HDFCLIFE','HEROMOTOCO','HINDALCO','HINDUNILVR','ICICIBANK','ITC','INDUSINDBK','INFY','JSWSTEEL','KOTAKBANK','LTIM','LT','M&M','MARUTI','NTPC','NESTLEIND','ONGC','POWERGRID','RELIANCE','SBILIFE','SBIN','SUNPHARMA','TCS','TATACONSUM','TATAMOTORS','TATASTEEL','TECHM','TITAN','UPL','ULTRACEMCO','WIPRO') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty MIDCAP 50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ACC','AUBANK','ABBOTINDIA','ABCAPITAL','ALKEM','ASHOKLEY','ASTRAL','AUROPHARMA','BALKRISIND','BANDHANBNK','BATAINDIA','BHARATFORG','BIOCON','COFORGE','CONCOR','CUMMINSIND','DALBHARAT','ESCORTS','FEDERALBNK','GODREJPROP','GUJGASLTD','HDFCAMC','HINDPETRO','IDFCFIRSTB','INDHOTEL','IGL','INDUSTOWER','JUBLFOOD','LTTS','LICHSGFIN','LUPIN','MRF','M&MFIN','MFSL','MPHASIS','NMDC','OBEROIRLTY','OFSS','PAGEIND','PERSISTENT','PETRONET','POLYCAB','PFC','RECLTD','SAIL','TATACOMM','UBL','IDEA','VOLTAS','ZEEL') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty SMALLCAP 50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 2 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ARE&M','ANGELONE','ANURAS','BIKAJI','BSOFT','CESC','CIEINDIA','CAMPUS','CDSL','CHAMBLFERT','CUB','CAMS','CYIENT','EXIDEIND','FINCABLES','GLENMARK','MEDANTA','GNFC','HFCL','HINDCOPPER','IDBI','IDFC','IRB','INDIAMART','IEX','IOB','JBCHEPHARM','JBMA','KEI','KALYANKJIL','MGL','MANAPPURAM','MRPL','NATIONALUM','PNBHOUSING','PVRINOX','PPLPHARMA','RBLBANK','RADICO','RAYMOND','REDINGTON','ROUTE','RENUKA','SONATSOFTW','SUZLON','TANLA','TEJASNET','UCOBANK','UTIAMC','WELSPUNLIV') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty Next 50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ABB','ADANIENSOL','ADANIGREEN','ATGL','AWL','AMBUJACEM','DMART','BAJAJHLDNG','BANKBARODA','BERGEPAINT','BEL','BOSCHLTD','CANBK','CHOLAFIN','COLPAL','DLF','DABUR','GAIL','GODREJCP','HAVELLS','HAL','ICICIGI','ICICIPRULI','IOC','IRCTC','NAUKRI','INDIGO','JINDALSTEL','LICI','MARICO','MUTHOOTFIN','PIIND','PIDILITIND','PGHH','PNB','SBICARD','SRF','MOTHERSON','SHREECEM','SHRIRAMFIN','SIEMENS','TVSMOTOR','TATAPOWER','TORNTPHARM','TRENT','MCDOWELL-N','VBL','VEDL','ZOMATO','ZYDUSLIFE') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty200 Momentum 30",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('ALKEM','AUROPHARMA','BAJAJ-AUTO','BEL','BHARATFORG','BHEL','COALINDIA','COLPAL','DLF','DRREDDY','ESCORTS','HEROMOTOCO','HAL','IPCALAB','L&TFH','LT','LUPIN','NMDC','NTPC','OBEROIRLTY','POLYCAB','PFC','PNB','RECLTD','SUNTV','TVSMOTOR','TATAMOTORS','RAMCOCEM','TRENT','ZYDUSLIFE') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty Midcap150 Momentum 50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 9 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('AIAENG','APLAPOLLO','AJANTPHARM','ALKEM','AUROPHARMA','BHARATFORG','BHEL','CGPOWER','CRISIL','ESCORTS','FACT','FORTIS','GICRE','HDFCAMC','IDFCFIRSTB','INDIANB','IRFC','IPCALAB','JSL','KPRMILL','KPITTECH','L&TFH','LINDEINDIA','LUPIN','MRF','LODHA','MAXHEALTH','MAZDOCK','METROBRAND','NHPC','NMDC','OBEROIRLTY','POLICYBZR','PERSISTENT','PHOENIXLTD','POLYCAB','PFC','PRESTIGE','RECLTD','SOLARINDS','SUNTV','SUNDARMFIN','SUNDRMFAST','SUPREMEIND','NIACL','RAMCOCEM','TORNTPOWER','UNOMINDA','UNIONBANK','ZFCVINDIA') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty SmCap Momentum 100",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('360ONE','AARTIDRUGS','AEGISCHEM','AMBER','APARINDS','ARE&M','AVANTIFEED','BALAMINES','BALRAMCHIN','BIRLACORPN','BLS','BSE','BSOFT','CANFINHOME','CASTROLIND','CDSL','CENTURYTEX','CERA','CGCL','CHAMBLFERT','CIEINDIA','COCHINSHIP','CREDITACC','CSBBANK','CYIENT','DELTACORP','ECLERX','ENGINERSIN','ERIS','FDC','FINCABLES','FINPIPE','FSL','GAEL','GLENMARK','GNFC','GODFRYPHLP','GPIL','GPPL','GRAPHITE','GSFC','HFCL','HINDCOPPER','IDFC','IEX','IIFL','INDIAMART','INTELLECT','IOB','IRCON','JBMA','JINDALSAW','JKLAKSHMI','JKPAPER','JYOTHYLAB','KARURVYSYA','KEI','KRBL','KSB','LUXIND','MANAPPURAM','MASTEK','MCX','METROPOLIS','MGL','MMTC','MOTILALOFS','NAM-INDIA','NATCOPHARM','NBCC','NCC','NETWORK18','NH','NLCINDIA','PCBL','PNBHOUSING','PNCINFRA','POLYMED','PRAJIND','QUESS','RADICO','RALLIS','REDINGTON','RHIM','RITES','SAFARI','SOBHA','SONATSOFTW','SUNTECK','SUVENPHAR','TANLA','TATAINVEST','TRITURBINE','TRIVENI','USHAMART','VIPIND','VTL','WELCORP','WELSPUNLIV','ZENSARTECH') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    },
    {
     "title": "Nifty SmCap Momentum 100",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 15, "y": 16 },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT time, iox.prices.\"Symbol\", AVG(prices.\"CZG\") AS \"avg_CZG\", AVG(prices.\"Price\") AS \"avg_price\" FROM iox.prices \nWHERE (time >= $__timeFrom AND time <= $__timeTo) AND iox.prices.\"Symbol\" IN ('360ONE','AARTIDRUGS','AEGISCHEM','AMBER','APARINDS','ARE&M','AVANTIFEED','BALAMINES','BALRAMCHIN','BIRLACORPN','BLS','BSE','BSOFT','CANFINHOME','CASTROLIND','CDSL','CENTURYTEX','CERA','CGCL','CHAMBLFERT','CIEINDIA','COCHINSHIP','CREDITACC','CSBBANK','CYIENT','DELTACORP','ECLERX','ENGINERSIN','ERIS','FDC','FINCABLES','FINPIPE','FSL','GAEL','GLENMARK','GNFC','GODFRYPHLP','GPIL','GPPL','GRAPHITE','GSFC','HFCL','HINDCOPPER','IDFC','IEX','IIFL','INDIAMART','INTELLECT','IOB','IRCON','JBMA','JINDALSAW','JKLAKSHMI','JKPAPER','JYOTHYLAB','KARURVYSYA','KEI','KRBL','KSB','LUXIND','MANAPPURAM','MASTEK','MCX','METROPOLIS','MGL','MMTC','MOTILALOFS','NAM-INDIA','NATCOPHARM','NBCC','NCC','NETWORK18','NH','NLCINDIA','PCBL','PNBHOUSING','PNCINFRA','POLYMED','PRAJIND','QUESS','RADICO','RALLIS','REDINGTON','RHIM','RITES','SAFARI','SOBHA','SONATSOFTW','SUNTECK','SUVENPHAR','TANLA','TATAINVEST','TRITURBINE','TRIVENI','USHAMART','VIPIND','VTL','WELCORP','WELSPUNLIV','ZENSARTECH') GROUP BY time, iox.prices.\"Symbol\" ORDER BY time"
      }
     ]
    }
   ]
  }
 ]
}