# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v .

    - name: List binaries
      run: |
        ls

    - name: Test
      run: go test -v .

    - name: Zip the binary
      uses: montudor/action-zip@v1.0.0
      with:
    # See montudor/action-zip README.md for more info
       args: zip stocktrend.zip ./stocktrend
          

    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      env:
        FILE: ./stocktrend.zip
        AWS_REGION: 'us-east-1'
        S3_BUCKET: stocktrend
        S3_KEY: artifacts/stocktrend-${{ github.run_number }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
          
