name: Start-Stop-EC2-Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  start-stop-ec2:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "ap-south-1"
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ vars.EC2INSTANCE }}

      - name: Sleep
        run: |
          sleep 30s

      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ vars.EC2INSTANCE }}
